# Generated by Django 4.0.5 on 2022-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='localization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
